apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: { duration: 15s }
      - setWeight: 50
      - pause: {}
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: demo-app
        image: nginx:1.15 # Initial version
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
  namespace: default
spec:
  selector:
    app: canary-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80