apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-analysis-demo
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: { duration: 30s }
      - setWeight: 50
      - analysis:
          templates:
          - templateName: success-rate
      - pause: { duration: 30s }
  selector:
    matchLabels:
      app: canary-analysis-demo
  template:
    metadata:
      labels:
        app: canary-analysis-demo
    spec:
      containers:
      - name: demo-app
        image: nginx:1.15 # Initial version
        ports:
        - containerPort: 80
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: default
spec:
  metrics:
  - name: success-rate
    interval: 10s
    count: 3
    successCondition: result.success >= 90
    provider:
      web:
        url: "http://canary-analysis-service.default.svc.cluster.local/IDONTEXIST"
        method: GET
---
apiVersion: v1
kind: Service
metadata:
  name: canary-analysis-service
  namespace: default
spec:
  selector:
    app: canary-analysis-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80