apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod
  namespace: default
spec:
  containers:
  - name: ssh-container
    image: ubuntu:latest
    command:
    - sleep
    - "3600"
    stdin: true
    tty: true
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "apt-get update && apt-get install -y curl"]